---
openapi: 3.0.1
info:
  title: API V2
  version: v2
paths:
  "/api/v2/books":
    get:
      summary: Book Listing
      tags:
      - Books
      parameters:
      - name: encounter
        in: query
        schema:
          type: object
          properties:
            user_id:
              type: integer
            book_id:
              type: integer
          required:
          - user_id
          - book_id
      responses:
        '200':
          description: fetch data
  "/api/v2/encounters":
    post:
      summary: Create an Encounter
      tags:
      - Encounters
      parameters: []
      responses:
        '201':
          description: encounter created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                patient_id:
                  type: integer
                provider_id:
                  type: integer
              required:
              - patient_id
              - provider_id
  "/api/v2/high_scores":
    get:
      summary: High Score Listing 2
      tags:
      - High Score
      responses:
        '200':
          description: fetch data
      parameters:
      - name: id
        in: query
        schema:
          type: string
  "/api/v2/high_scores/{id}":
    get:
      summary: High Score Show
      tags:
      - High Score
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Get single record
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
